---
name: traefik

networks:
  frontend:
    # Contains all the services that will be routed to
    external: true
  internal:
    # Contains traefik, socket proxy, and traefik-tunnel
    external: false
    name: traefik_internal

volumes:
  socket-proxy:

services:
  traefik-external:
    image: docker.io/traefik:v3
    container_name: traefik-external
    command:
      - "--configFile=/traefik/traefik.yaml"
    read_only: true
    user: "${TRAEFIK_SRV_ID:-2001}:${TRAEFIK_GROUP_ID:-2001}"
    group_add:
      - "${DOCKER_GROUP_ID_CERT_MANAGER:-2013}"
    security_opt:
      - no-new-privileges:true
    sysctls:
      # allow rootless container to access ports < 1024
      net.ipv4.ip_unprivileged_port_start: 80
    depends_on:
      crowdsec:
        condition: service_healthy
      socket-proxy:
        condition: service_healthy
        restart: true
    restart: unless-stopped
    healthcheck:
      # https://doc.traefik.io/traefik/operations/cli/#healthcheck
      test: [CMD, traefik, healthcheck, "--ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    ports:
      - "${HOST_IP:-10.0.0.13}:80:80/tcp"
      - "${HOST_IP:-10.0.0.13}:443:443/tcp"
    environment:
      CROWDSEC_TRAEFIK_BOUNCER_TOKEN: "${CROWDSEC_TRAEFIK_BOUNCER_TOKEN}"
      TZ: "${TZ:-America/New_York}"
    networks:
      - frontend
      - internal
    volumes:
      - ./config-external/traefik.yaml:/traefik/traefik.yaml:ro
      - ./config-external/conf/:/traefik/conf/:ro
      - ./config-external/plugins/:/plugins-storage/:rw
      - ./config-external/certs/:/traefik/certs:rw
      - ./config-external/static-certs/:/traefik/static-certs-lhr1/:ro
      - ./config-external/static-certs-slc1/:/traefik/static-certs-slc1/:ro
      - ./config-external/logs:/var/log/traefik:rw
      - ./config-external/ban.html:/traefik/ban.html:ro
      - ./config-external/captcha.html:/traefik/captcha.html:ro
    labels:
      # Management only exposed internally
      traefik.enable: true
      traefik.docker.network: frontend
      traefik.http.services.traefikexternal-prod-1.loadBalancer.server.port: 8080
      traefik.http.routers.traefikexternal-prod-1-http.entrypoints: web
      traefik.http.routers.traefikexternal-prod-1-http.rule: "Host(`traefik-external.iad1vpn.jakerob.pro`)  && !PathPrefix(`/ping`)"
      traefik.http.routers.traefikexternal-prod-1-http.middlewares: "websecure-redirect-permanent@file"
      traefik.http.routers.traefikexternal-prod-1-https.entrypoints: websecure
      traefik.http.routers.traefikexternal-prod-1-https.rule: "Host(`traefik-external.iad1vpn.jakerob.pro`)  && !PathPrefix(`/ping`)"
      traefik.http.routers.traefikexternal-prod-1-https.tls: true
      traefik.http.routers.traefikexternal-prod-1-https.tls.certresolver: cloudflare

  traefik-internal:
    image: docker.io/traefik:v3
    container_name: traefik-internal
    command:
      - "--configFile=/traefik/traefik.yaml"
    read_only: true
    user: "${DOCKER_USER_ID:-2001}:${DOCKER_GROUP_ID:-2001}"
    security_opt:
      - no-new-privileges:true
    sysctls:
      # allow rootless container to access ports < 1024
      net.ipv4.ip_unprivileged_port_start: 80
    depends_on:
      socket-proxy:
        condition: service_healthy
        restart: true
    restart: unless-stopped
    healthcheck:
      # https://doc.traefik.io/traefik/operations/cli/#healthcheck
      test: [CMD, traefik, healthcheck, "--ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    ports:
      # Bind on secure IP (local, VPN) only
      - "${VPN_IP:-100.109.65.68}:80:80/tcp"
      - "${VPN_IP:-100.109.65.68}:443:443/tcp"
    environment:
      CF_DNS_API_TOKEN: "${CF_DNS_API_TOKEN}"
      TZ: "${TZ:-America/New_York}"
    networks:
      - frontend
      - internal
    volumes:
      - ./config-internal/traefik.yaml:/traefik/traefik.yaml:ro
      - ./config-internal/conf/:/traefik/conf/:rw
      - ./config-internal/certs/:/traefik/certs/:rw
      # access docker socket via proxy read-only
      - socket-proxy:/var/run
    labels:
      # Management only exposed internally
      traefik.enable: true
      traefik.docker.network: frontend
      traefik.http.services.traefikinternal-prod-1.loadBalancer.server.port: 8080
      traefik.http.routers.traefikinternal-prod-1-http.entrypoints: web
      traefik.http.routers.traefikinternal-prod-1-http.rule: "Host(`traefik-internal.iad1vpn.jakerob.pro`) && !PathPrefix(`/ping`)"
      traefik.http.routers.traefikinternal-prod-1-http.middlewares: "websecure-redirect-permanent@file"
      traefik.http.routers.traefikinternal-prod-1-https.entrypoints: websecure
      traefik.http.routers.traefikinternal-prod-1-https.rule: "Host(`traefik-internal.iad1vpn.jakerob.pro`) && !PathPrefix(`/ping`)"
      traefik.http.routers.traefikinternal-prod-1-https.tls: true
      traefik.http.routers.traefikinternal-prod-1-https.tls.certresolver: cloudflare
  crowdsec:
    image: docker.io/crowdsecurity/crowdsec:latest
    container_name: crowdsec
    command: "-t"
    user: "${DOCKER_USER_ID:-2001}:${DOCKER_GROUP_ID:-2001}"
    restart: unless-stopped
    healthcheck:
      interval: 10s
      retries: 15
      test:
        - CMD
        - cscli
        - capi
        - status
      timeout: 10s
    environment:
      COLLECTIONS: crowdsecurity/traefik crowdsecurity/http-cve crowdsecurity/base-http-scenarios crowdsecurity/appsec-virtual-patching crowdsecurity/appsec-generic-rules
      CUSTOM_HOSTNAME: crowdsec
      ENROLL_INSTANCE_NAME: pangolin-crowdsec
      ENROLL_TAGS: docker
      GID: "${DOCKER_GROUP_ID:-2001}"
      UID: "${DOCKER_USER_ID:-2001}"
      PARSERS: crowdsecurity/whitelists
      BOUNCER_KEY_TRAEFIK: "${CROWDSEC_TRAEFIK_BOUNCER_TOKEN}"
    networks:
      - internal
    volumes:
      - ./acquis.yaml:/etc/crowdsec/acquis.yaml:ro
      - ./config-crowdsec:/etc/crowdsec
      - ./crowdsec-db/:/var/lib/crowdsec/data
      - ./config-external/logs:/var/log/traefik
    labels:
      traefik.enable: "false"

  socket-proxy:
    image: docker.io/11notes/socket-proxy:2
    container_name: traefik-socket-proxy
    read_only: true
    user: "0:${DOCKER_GROUP_ID}" # Lookup the docker group ID using `getent group docker`
    restart: unless-stopped
    environment:
      SOCKET_PROXY_UID: "${TRAEFIK_SRV_ID:-2001}"
      SOCKET_PROXY_GID: "${TRAEFIK_GROUP_ID:-2001}"
    networks:
      - internal
    volumes:
      # mount host docker socket, the :ro does not mean read-only for the socket, just for the actual file
      - /run/docker.sock:/run/docker.sock:ro
      # this socket is run as 1000:1000, not as root!
      - socket-proxy:/run/proxy

  whoami-external:
    image: docker.io/traefik/whoami
    container_name: whoami-external
    command: "--verbose"
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - frontend
    labels:
      traefik.enable: true
      traefik.external: true
      traefik.http.routers.whoamiexternal-prod-1-http.entrypoints: web
      traefik.http.routers.whoamiexternal-prod-1-http.rule: Host(`whoami.iad1.jakerob.pro`)
      traefik.http.routers.whoamiexternal-prod-1-https.entrypoints: websecure
      traefik.http.routers.whoamiexternal-prod-1-https.rule: Host(`whoami.iad1.jakerob.pro`)
      traefik.http.routers.whoamiexternal-prod-1-https.tls: true
      traefik.http.routers.whoamiexternal-prod-1-https.tls.certresolver: production

  whoami-internal:
    image: docker.io/traefik/whoami
    container_name: whoami-internal
    command: "--verbose"
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - frontend
    labels:
      traefik.enable: true
      traefik.http.routers.whoamiinternal-prod-1-http.entrypoints: web
      traefik.http.routers.whoamiinternal-prod-1-http.rule: Host(`whoami.iad1vpn.jakerob.pro`)
      traefik.http.routers.whoamiinternal-prod-1-https.entrypoints: websecure
      traefik.http.routers.whoamiinternal-prod-1-https.rule: Host(`whoami.iad1vpn.jakerob.pro`)
      traefik.http.routers.whoamiinternal-prod-1-https.tls: true
      traefik.http.routers.whoamiinternal-prod-1-https.tls.certresolver: cloudflare
