---
name: immich

networks:
  frontend:
    external: true
  internal:
    external: false

volumes:
  model-cache:
  database:

services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:v2.4.1
    container_name: immich_server
    user: "${DOCKER_USER_ID:-2004}:${DOCKER_GROUP_ID:-2004}"
    security_opt:
      # Prevent escalation of privileges after the container is started
      - no-new-privileges:true
    cap_drop:
      # Prevent access to raw network traffic
      - NET_RAW
    depends_on:
      - redis
      - database
    restart: unless-stopped
    healthcheck:
      disable: false
    environment:
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_USERNAME: "${DB_USERNAME:-postgres}"
      DB_HOSTNAME: database
      DB_DATABASE_NAME: "${DB_DATABASE_NAME:-immich}"
    networks:
      - frontend
      - internal
    # devices:
    #   - /dev/dri:/dev/dri
    volumes:
      - /nfs/immich:/data
      - /etc/localtime:/etc/localtime:ro
    labels:
      traefik.enable: true
      traefik.docker.network: frontend
      traefik.http.routers.immich-prod-1-http.entrypoints: web
      traefik.http.routers.immich-prod-1-http.rule: Host(`photos.autovation.com`)
      traefik.http.routers.immich-prod-1-http.middlewares: "websecure-redirect-permanent@file"
      traefik.http.routers.immich-prod-1-https.entrypoints: websecure
      traefik.http.routers.immich-prod-1-https.rule: Host(`photos.autovation.com`)
      traefik.http.routers.immich-prod-1-https.tls: true
      traefik.http.routers.immich-prod-1-https.tls.certresolver: cloudflare

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:v2.4.1
        # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware-acceleration
        #   file: hwaccel.ml.yml
        #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    container_name: immich_machine_learning
        # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
        # Example tag: ${IMMICH_VERSION:-release}-cuda
    user: "${DOCKER_USER_ID:-2004}:${DOCKER_GROUP_ID:-2004}"
    security_opt:
      # Prevent escalation of privileges after the container is started
      - no-new-privileges:true
    cap_drop:
      # Prevent access to raw network traffic
      - NET_RAW
    restart: unless-stopped
    healthcheck:
      disable: false
    environment:
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_USERNAME: "${DB_USERNAME:-postgres}"
      DB_HOSTNAME: database
      DB_DATABASE_NAME: "${DB_DATABASE_NAME:-immich}"
    networks:
      - internal
    volumes:
      - model-cache:/cache

  redis:
    image: "docker.io/valkey/valkey:9@sha256:fb8d272e529ea567b9bf1302245796f21a2672b8368ca3fcb938ac334e613c8f"
    container_name: immich_redis
    restart: unless-stopped
    healthcheck:
      test: "redis-cli ping || exit 1"
    networks:
      - internal

  database:
    image: "ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23"
    container_name: immich_postgres
    user: "${DOCKER_USER_ID:-2004}:${DOCKER_GROUP_ID:-2004}"
    restart: unless-stopped
    depends_on:
      chown:
        condition: service_completed_successfully
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USERNAME:-postgres}"
      POSTGRES_DB: "${DB_DATABASE_NAME:-immich}"
      POSTGRES_INITDB_ARGS: "--data-checksums"
    networks:
      - internal
    volumes:
      - database:/var/lib/postgresql/data
    shm_size: 128mb

  # This image will mount the volume and then simply execute chown on the parent folder for the UID/GID specified.
  chown:
    image: alpine
    command:
      - |
        chown -R ${DOCKER_USER_ID:-2004}:${DOCKER_GROUP_ID:-2004} /var/lib/postgresql/data
    networks: []
    volumes:
      - database:/var/lib/postgresql/data
    entrypoint: [/bin/ash, "-c"]
