---
name: mealie

networks:
  frontend:
    external: true

services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v3.5.0
    container_name: mealie
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    environment:
      OIDC_AUTH_ENABLED: true
      OIDC_SIGNUP_ENABLED: true
      OIDC_CONFIGURATION_URL: https://pocket-id.iad1.jakerob.pro/.well-known/openid-configuration
      OIDC_CLIENT_ID: "${OIDC_CLIENT_ID}"
      OIDC_CLIENT_SECRET: "${OIDC_CLIENT_SECRET}"
      OIDC_PROVIDER_NAME: Pocket ID
      OIDC_AUTO_REDIRECT: false
      ALLOW_SIGNUP: "true"
      PUID: 1002
      PGID: 1002
      TZ: "${TZ:-Europe/London}"
      MAX_WORKERS: 1
      WEB_CONCURRENCY: 1
      BASE_URL: https://mealie.jakerob.pro
    networks:
      - frontend
    volumes:
      - ./data:/app/data/
    deploy:
      resources:
        limits:
          memory: 1000M
    labels:
      traefik.enable: true
      traefik.external: true
      traefik.http.middlewares.mealie-prod-1-websecure-redirect.redirectscheme.scheme: https
      traefik.http.routers.mealie-prod-1-http.entrypoints: web
      traefik.http.routers.mealie-prod-1-http.rule: Host(`mealie.jakerob.pro`)
      traefik.http.routers.mealie-prod-1-http.middlewares: mealie-prod-1-websecure-redirect
      traefik.http.routers.mealie-prod-1-https.entrypoints: websecure
      traefik.http.routers.mealie-prod-1-https.rule: Host(`mealie.jakerob.pro`)
      traefik.http.routers.mealie-prod-1-https.tls: true
      traefik.http.routers.mealie-prod-1-https.tls.certresolver: production
