---
name: astro-self-host-demo

networks:
  frontend:
    external: true

services:
  astro-self-host-example:
    image: ghcr.io/jacob-roberts/astro-self-host-example:0.0.6
    container_name: astro-self-host-example
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - frontend
    labels:
      traefik.enable: true
      traefik.http.services.astroselfhostexample-demo-1.loadBalancer.server.port: 4321
      traefik.http.routers.astroselfhostexample-demo-1-http.entrypoints: web
      traefik.http.routers.astroselfhostexample-demo-1-http.rule: Host(`astroselfhostexample.lhr1.jakerob.pro`)
      traefik.http.routers.astroselfhostexample-demo-1-http.middlewares: "websecure-redirect-permanent@file"
      traefik.http.routers.astroselfhostexample-demo-1-https.entrypoints: websecure
      traefik.http.routers.astroselfhostexample-demo-1-https.rule: Host(`astroselfhostexample.lhr1.jakerob.pro`)
      traefik.http.routers.astroselfhostexample-demo-1-https.middlewares: "testheader@docker"
      traefik.http.routers.astroselfhostexample-demo-1-https.tls: true
      traefik.http.routers.astroselfhostexample-demo-1-https.tls.certresolver: cloudflare

      traefik.http.middlewares.testheader.headers.accesscontrolallowmethods: "*"
      traefik.http.middlewares.testheader.headers.accesscontrolallowheaders: "*"
      traefik.http.middlewares.testheader.headers.accesscontrolalloworiginlist: https://astroselfhostexamplestatic.lhr1.jakerob.pro
      traefik.http.middlewares.testheader.headers.accesscontrolmaxage: 100
      traefik.http.middlewares.testheader.headers.addvaryheader: true

  astro-self-host-example-static:
    image: docker.io/y4m4/s3www:latest
    container_name: astro-self-host-example-static
    command:
      - "-endpoint=https://minioapi.lhr1.jakerob.pro"
      - "-accessKey=$ACCESS_KEY"
      - "-secretKey=$SECRET_KEY"
      - "-bucket=astro-demo"
      - "-address=0.0.0.0:8080"
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - frontend
    labels:
      traefik.enable: true
      traefik.http.services.astroselfhostexamplestatic-demo-1.loadBalancer.server.port: 8080
      traefik.http.routers.astroselfhostexamplestatic-demo-1-http.entrypoints: web
      traefik.http.routers.astroselfhostexamplestatic-demo-1-http.rule: Host(`astroselfhostexamplestatic.lhr1.jakerob.pro`)
      traefik.http.routers.astroselfhostexamplestatic-demo-1-http.middlewares: "websecure-redirect-permanent@file"
      traefik.http.routers.astroselfhostexamplestatic-demo-1-https.entrypoints: websecure
      traefik.http.routers.astroselfhostexamplestatic-demo-1-https.rule: Host(`astroselfhostexamplestatic.lhr1.jakerob.pro`)
      traefik.http.routers.astroselfhostexamplestatic-demo-1-https.tls: true
      traefik.http.routers.astroselfhostexamplestatic-demo-1-https.tls.certresolver: cloudflare
