---
name: traefik

networks:
  frontend:
    external: true
  internal:
    external: false
  tunnel:
    external: true

services:
  traefik:
    image: docker.io/traefik:v3
    container_name: traefik-prod-1
    user: 1000:1000
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

    ports:
      - 192.168.97.133:80:80
      - 192.168.97.133:443:443
    environment:
      CF_DNS_API_TOKEN: "${CF_DNS_API_TOKEN}"
    networks:
      - frontend
      - internal
    volumes:
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./config/conf/:/etc/traefik/conf/
      - ./config/certs/:/etc/traefik/certs/
    labels:
      traefik.enable: true
      traefik.docker.network: frontend
      traefik.http.services.traefik-prod-1.loadBalancer.server.port: 8080
      traefik.http.routers.traefik-prod-1-http.entrypoints: web
      traefik.http.routers.traefik-prod-1-http.rule: Host(`traefik.slc1.jakerob.pro`)
      traefik.http.routers.traefik-prod-1-http.middlewares: "websecure-redirect-permanent@file"
      traefik.http.routers.traefik-prod-1-https.entrypoints: websecure
      traefik.http.routers.traefik-prod-1-https.rule: Host(`traefik.slc1.jakerob.pro`)
      traefik.http.routers.traefik-prod-1-https.tls: true
      traefik.http.routers.traefik-prod-1-https.tls.certresolver: cloudflare
  traefik-tunnel:
    image: docker.io/traefik:v3
    container_name: traefik-tunnel
    user: 1000:1000
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

    ports:
      # Bind on Tailscale interface only
      - 100.95.11.23:80:80
    networks:
      - tunnel
      - internal
    volumes:
      - ./config-tunnel/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./config-tunnel/conf/:/etc/traefik/conf/
    labels:
      traefik.enable: true
      traefik.http.services.traefiktunnel-prod-1.loadBalancer.server.port: 8080
      traefik.http.routers.traefiktunnel-prod-1-http.entrypoints: web
      traefik.http.routers.traefiktunnel-prod-1-http.rule: Host(`traefik-tunnel.slc1.jakerob.pro`)
      traefik.http.routers.traefiktunnel-prod-1-http.middlewares: "websecure-redirect-permanent@file"
      traefik.http.routers.traefiktunnel-prod-1-https.entrypoints: websecure
      traefik.http.routers.traefiktunnel-prod-1-https.rule: Host(`traefik-tunnel.slc1.jakerob.pro`)
      traefik.http.routers.traefiktunnel-prod-1-https.tls: true
      traefik.http.routers.traefiktunnel-prod-1-https.tls.certresolver: cloudflare
  socket-proxy:
    image: lscr.io/linuxserver/socket-proxy:latest
    container_name: traefik-socket-proxy
    read_only: true
    restart: unless-stopped
    environment:
      - ALLOW_START=0 #optional
      - ALLOW_STOP=0 #optional
      - ALLOW_RESTARTS=0 #optional
      - AUTH=0 #optional
      - BUILD=0 #optional
      - COMMIT=0 #optional
      - CONFIGS=0 #optional
      - CONTAINERS=1 #optional
      - DISABLE_IPV6=0 #optional
      - DISTRIBUTION=0 #optional
      - EVENTS=1 #optional
      - EXEC=0 #optional
      - IMAGES=0 #optional
      - INFO=0 #optional
      - NETWORKS=1 #optional
      - NODES=0 #optional
      - PING=1 #optional
      - POST=0 #optional
      - PLUGINS=0 #optional
      - SECRETS=0 #optional
      - SERVICES=1 #optional
      - SESSION=0 #optional
      - SWARM=0 #optional
      - SYSTEM=0 #optional
      - TASKS=1 #optional
      - VERSION=1 #optional
      - VOLUMES=0 #optional
    networks:
      - internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    tmpfs:
      - /run

  whoami:
    image: docker.io/traefik/whoami
    container_name: whoami-prod-1
    command: "--verbose"
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - frontend
    labels:
      traefik.enable: true
      traefik.http.routers.whoami-prod-1-http.entrypoints: web
      traefik.http.routers.whoami-prod-1-http.rule: Host(`whoami.slc1.jakerob.pro`)
      traefik.http.routers.whoami-prod-1-http.middlewares: "websecure-redirect-permanent@file"
      traefik.http.routers.whoami-prod-1-https.entrypoints: websecure
      traefik.http.routers.whoami-prod-1-https.rule: Host(`whoami.slc1.jakerob.pro`)
      traefik.http.routers.whoami-prod-1-https.tls: true
      traefik.http.routers.whoami-prod-1-https.tls.certresolver: cloudflare

  whoami-tunnel:
    image: docker.io/traefik/whoami
    container_name: whoami-tunnel
    command: "--verbose"
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - tunnel
    labels:
      traefik.enable: true
      traefik.tunnel-external: true
      traefik.http.routers.whoamitunnel-prod-1-http.entrypoints: web
      traefik.http.routers.whoamitunnel-prod-1-http.rule: Host(`whoami-tunnel-slc1.jakerob.pro`)
