---
name: paperless

networks:
  frontend:
    external: true
  internal:
    external: false

services:
  broker:
    image: docker.io/library/redis:8
    user: "${DOCKER_USER_ID:-2019}:${DOCKER_GROUP_ID:-2019}"
    restart: unless-stopped
    networks:
      - internal
    volumes:
      - ./redisdata:/data
  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    user: "${DOCKER_USER_ID:-2019}:${DOCKER_GROUP_ID:-2019}"
    depends_on:
      - broker
    restart: unless-stopped
    environment:
      PAPERLESS_SECRET_KEY: "${PAPERLESS_SECRET_KEY}"
      PAPERLESS_URL: https://paperless.lhr1.jakerob.pro
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_APPS: allauth.socialaccount.providers.openid_connect
      USERMAP_UID: "${DOCKER_USER_ID:-2019}"
      USERMAP_GID: "${DOCKER_GROUP_ID:-2019}"
      PAPERLESS_ADMIN_USER: "${PAPERLESS_ADMIN_USER}"
      PAPERLESS_ADMIN_MAIL: "${PAPERLESS_ADMIN_MAIL}"
      PAPERLESS_ADMIN_PASSWORD: "${PAPERLESS_ADMIN_PASSWORD}"
      PAPERLESS_SOCIALACCOUNT_PROVIDERS: >
        {
          "openid_connect": {
            "APPS": [
              {
                "provider_id": "pocketid",
                "name": "Pocket ID",
                "client_id": "${PAPERLESS_SOCIALACCOUNT_CLIENT_ID}",
                "secret": "${PAPERLESS_SOCIALACCOUNT_CLIENT_SECRET}",
                "settings": {
                  "server_url": "https://pocket-id.lhr1.jakerob.pro/.well-known/openid-configuration"
                }
              }
            ],
            "OAUTH_PKCE_ENABLED": "True"
          }
        }
    networks:
      - frontend
      - internal
    volumes:
      - ./data:/usr/src/paperless/data
      - /media/roberts-data/paperless:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    labels:
      traefik.enable: true
      traefik.docker.network: frontend
      traefik.http.services.paperless-prod-1.loadBalancer.server.port: 8000
      traefik.http.routers.paperless-prod-1-http.entrypoints: web
      traefik.http.routers.paperless-prod-1-http.rule: Host(`paperless.lhr1.jakerob.pro`)
      traefik.http.routers.paperless-prod-1-http.middlewares: "websecure-redirect-permanent@file"
      traefik.http.routers.paperless-prod-1-https.entrypoints: websecure
      traefik.http.routers.paperless-prod-1-https.rule: Host(`paperless.lhr1.jakerob.pro`)
      traefik.http.routers.paperless-prod-1-https.tls: true
      traefik.http.routers.paperless-prod-1-https.tls.certresolver: cloudflare
