---
name: grafana-alloy

networks:
  frontend:
    external: true
  otel:
    external: true

services:
  alloy:
    image: docker.io/grafana/alloy:latest
    container_name: alloy
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    networks:
      - frontend
      - otel
    volumes:
      - ./config/config.alloy:/etc/alloy/config.alloy:ro
    environment:
      - TEMPO_URL
      - TEMPO_USER
      - LOKI_URL
      - LOKI_USER_ID
      - GRAFANA_CLOUD_TOKEN
    labels:
      traefik.enable: true
      traefik.http.services.grafana-alloy-prod-1.loadBalancer.server.port: 12345
      traefik.http.routers.grafana-alloy-prod-1-http.entrypoints: web
      traefik.http.routers.grafana-alloy-prod-1-http.rule: Host(`grafana-alloy.iad1vpn.jakerob.pro`)
      traefik.http.routers.grafana-alloy-prod-1-http.middlewares: "websecure-redirect-permanent@file"
      traefik.http.routers.grafana-alloy-prod-1-https.entrypoints: websecure
      traefik.http.routers.grafana-alloy-prod-1-https.rule: Host(`grafana-alloy.iad1vpn.jakerob.pro`)
      traefik.http.routers.grafana-alloy-prod-1-https.tls: true
      traefik.http.routers.grafana-alloy-prod-1-https.tls.certresolver: cloudflare
