http:
  routers:
    ping-http:
      rule: "Host(`traefik-internal.iad1vpn.jakerob.pro`) && PathPrefix(`/ping`)"
      service: "ping@internal"
      entryPoints:
        - web
    ping-https:
      rule: "Host(`traefik-internal.iad1vpn.jakerob.pro`) && PathPrefix(`/ping`)"
      service: "ping@internal"
      entryPoints:
        - websecure
      tls: {}
