tls:
  certificates:
    - certFile: /traefik/static-certs-lhr1/whoami-tunnel.lhr1.jakerob.pro/certificate.crt
      keyFile: /traefik/static-certs-lhr1/whoami-tunnel.lhr1.jakerob.pro/privatekey.key
    - certFile: /traefik/static-certs-lhr1/pocket-id.lhr1.jakerob.pro/certificate.crt
      keyFile: /traefik/static-certs-lhr1/pocket-id.lhr1.jakerob.pro/privatekey.key
    - certFile: /traefik/static-certs-lhr1/photos.jakerob.pro/certificate.crt
      keyFile: /traefik/static-certs-lhr1/photos.jakerob.pro/privatekey.key
    - certFile: /traefik/static-certs-lhr1/jellyfin.jakerob.pro/certificate.crt
      keyFile: /traefik/static-certs-lhr1/jellyfin.jakerob.pro/privatekey.key
    - certFile: /traefik/static-certs-lhr1/karakeep.jakerob.pro/certificate.crt
      keyFile: /traefik/static-certs-lhr1/karakeep.jakerob.pro/privatekey.key
    - certFile: /traefik/static-certs-lhr1/calibre.jakerob.pro/certificate.crt
      keyFile: /traefik/static-certs-lhr1/calibre.jakerob.pro/privatekey.key
    - certFile: /traefik/static-certs-slc1/whoami-tunnel.slc1.jakerob.pro/certificate.crt
      keyFile: /traefik/static-certs-slc1/whoami-tunnel.slc1.jakerob.pro/privatekey.key
    - certFile: /traefik/static-certs-slc1/auth.autovation.com/certificate.crt
      keyFile: /traefik/static-certs-slc1/auth.autovation.com/privatekey.key
    - certFile: /traefik/static-certs-slc1/photos.autovation.com/certificate.crt
      keyFile: /traefik/static-certs-slc1/photos.autovation.com/privatekey.key
