http:
  middlewares:
    # -- (Optional) Redirect HTTP to HTTPS
    websecure-redirect:
      redirectScheme:
        scheme: https
    websecure-redirect-permanent:
      redirectScheme:
        scheme: https
        permanent: true
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true
