---

services:
  loki:
    image: docker.io/grafana/loki:2.9.17
    command: "-config.file=/etc/loki/local-config.yaml"

    ports:
      - 3100:3100
  promtail:
    image: docker.io/grafana/promtail:2.9.7
    command: "-config.file=/etc/promtail/config.yml"
    volumes:
      - /var/log:/var/log
