---

services:
  loki:
    image: grafana/loki:2.9.7
    command: "-config.file=/etc/loki/local-config.yaml"

    ports:
      - 3100:3100
  promtail:
    image: grafana/promtail:3.6.3
    command: "-config.file=/etc/promtail/config.yml"
    volumes:
      - /var/log:/var/log
