---
name: homepage

networks:
  frontend:
    external: true

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.9.3
    container_name: homepage-prod-1
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    environment:
      PUID: ${DOCKER_USER_ID:-2008}
      PGID: ${DOCKER_GROUP_ID:-2008}
      LOG_LEVEL: debug
      HOMEPAGE_VAR_PROXMOX_USERNAME: "${HOMEPAGE_VAR_PROXMOX_USERNAME}"
      HOMEPAGE_VAR_PROXMOX_PASSWORD: "${HOMEPAGE_VAR_PROXMOX_PASSWORD}"
      HOMEPAGE_VAR_PORTAINER_KEY: "${HOMEPAGE_VAR_PORTAINER_KEY}"
      HOMEPAGE_VAR_IMMICH_KEY: "${HOMEPAGE_VAR_IMMICH_KEY}"
      HOMEPAGE_VAR_JELLYFIN_KEY: "${HOMEPAGE_VAR_JELLYFIN_KEY}"
      HOMEPAGE_VAR_NEXTCLOUD_KEY: "${HOMEPAGE_VAR_NEXTCLOUD_KEY}"
      HOMEPAGE_VAR_AUTHENTIK_KEY: "${HOMEPAGE_VAR_AUTHENTIK_KEY}"
      HOMEPAGE_VAR_PROWLARR_KEY: "${HOMEPAGE_VAR_PROWLARR_KEY}"
      HOMEPAGE_VAR_SONARR_KEY: "${HOMEPAGE_VAR_SONARR_KEY}"
      HOMEPAGE_VAR_RADARR_KEY: "${HOMEPAGE_VAR_RADARR_KEY}"
      HOMEPAGE_VAR_QBITTORRENT_USERNAME: "${HOMEPAGE_VAR_QBITTORRENT_USERNAME}"
      HOMEPAGE_VAR_QBITTORRENT_PASSWORD: "${HOMEPAGE_VAR_QBITTORRENT_PASSWORD}"
    networks:
      - frontend
    volumes:
      - ./config:/app/config:ro
      - ./images:/app/public/images:ro
      - ./icons:/app/public/icons:ro
      # - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      traefik.enable: true
      traefik.http.routers.homepage-prod-1-http.entrypoints: web
      traefik.http.routers.homepage-prod-1-http.rule: Host(`homepage.lhr1.jakerob.pro`)
      traefik.http.routers.homepage-prod-1-http.middlewares: "websecure-redirect-permanent@file"
      traefik.http.routers.homepage-prod-1-https.entrypoints: websecure
      traefik.http.routers.homepage-prod-1-https.rule: Host(`homepage.lhr1.jakerob.pro`)
      traefik.http.routers.homepage-prod-1-https.tls: true
      traefik.http.routers.homepage-prod-1-https.tls.certresolver: cloudflare
