---
name: karakeep

networks:
  frontend:
    external: true
  internal:
    external: false
    name: karakeep_internal

services:
  web:
    image: ghcr.io/karakeep-app/karakeep:release
    user: "${DOCKER_USER_ID:-2009}:${DOCKER_GROUP_ID:-2009}"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      NEXTAUTH_SECRET: "${NEXTAUTH_SECRET}"
      NEXTAUTH_URL: "${NEXTAUTH_URL:-https://karakeep.jakerob.pro}"
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      DISABLE_SIGNUPS: false
      DISABLE_PASSWORD_AUTH: true
      OAUTH_WELLKNOWN_URL: "${OAUTH_WELLKNOWN_URL:-https://pocket-id.lhr1.jakerob.pro/.well-known/openid-configuration}"
      OAUTH_CLIENT_ID: "${OAUTH_CLIENT_ID}"
      OAUTH_CLIENT_SECRET: "${OAUTH_CLIENT_SECRET}"
      OAUTH_PROVIDER_NAME: "${OAUTH_PROVIDER_NAME:-PocketID}"

      # OPENAI_API_KEY: ...

      # You almost never want to change the value of the DATA_DIR variable.
      # If you want to mount a custom directory, change the volume mapping above instead.
      DATA_DIR: /data # DON'T CHANGE THIS
    networks:
      - frontend
      - internal
    volumes:
      - ./data:/data
    labels:
      traefik.enable: true
      traefik.http.services.karakeep-prod-1.loadBalancer.server.port: 3000
      traefik.http.routers.karakeep-prod-1-http.entrypoints: web
      traefik.http.routers.karakeep-prod-1-http.rule: Host(`karakeep.jakerob.pro`)
      traefik.http.routers.karakeep-prod-1-http.middlewares: "websecure-redirect-permanent@file"
      traefik.http.routers.karakeep-prod-1-https.entrypoints: websecure
      traefik.http.routers.karakeep-prod-1-https.rule: Host(`karakeep.jakerob.pro`)
      traefik.http.routers.karakeep-prod-1-https.tls: true
      traefik.http.routers.karakeep-prod-1-https.tls.certresolver: cloudflare
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    command:
      - "--no-sandbox"
      - "--disable-gpu"
      - "--disable-dev-shm-usage"
      - "--remote-debugging-address=0.0.0.0"
      - "--remote-debugging-port=9222"
      - "--hide-scrollbars"
    restart: unless-stopped
    networks:
      - internal
  meilisearch:
    image: docker.io/getmeili/meilisearch:v1.35.1
    user: "${DOCKER_USER_ID:-2009}:${DOCKER_GROUP_ID:-2009}"
    restart: unless-stopped
    environment:
      MEILI_MASTER_KEY: "${MEILI_MASTER_KEY}"
      MEILI_NO_ANALYTICS: "true"
    networks:
      - internal
    volumes:
      - ./meilisearch:/meili_data
