---
name: portainer

networks:
  frontend:
    external: true
  internal:
    external: false

services:
  portainer:
    image: portainer/portainer-ce:2.26.1-alpine
    container_name: portainer
    command: "-H tcp://socket-proxy:2375"
    user: 1000:1000
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - frontend
      - internal
    volumes:
      - ./data:/data
    labels:
      traefik.enable: true
      traefik.docker.network: frontend
      traefik.http.services.portainer-prod-1.loadbalancer.server.port: '9000'
      traefik.http.services.portainer-prod-1.loadbalancer.server.scheme: http
      traefik.http.routers.portainer-prod-1-http.entrypoints: web
      traefik.http.routers.portainer-prod-1-http.rule: Host(`portainer.lhr1.jakerob.pro`)
      traefik.http.routers.portainer-prod-1-http.middlewares: "websecure-redirect-permanent@file"
      traefik.http.routers.portainer-prod-1-https.entrypoints: websecure
      traefik.http.routers.portainer-prod-1-https.rule: Host(`portainer.lhr1.jakerob.pro`)
      traefik.http.routers.portainer-prod-1-https.tls: true
      traefik.http.routers.portainer-prod-1-https.tls.certresolver: cloudflare
  socket-proxy:
    image: lscr.io/linuxserver/socket-proxy:latest
    container_name: portainer-socket-proxy
    read_only: true
    restart: unless-stopped
    environment:
      - ALLOW_START=1 #optional
      - ALLOW_STOP=1 #optional
      - ALLOW_RESTARTS=1 #optional
      - AUTH=0 #optional
      - BUILD=0 #optional
      - COMMIT=0 #optional
      - CONFIGS=0 #optional
      - CONTAINERS=1 #optional
      - DISABLE_IPV6=0 #optional
      - DISTRIBUTION=0 #optional
      - EVENTS=1 #optional
      - EXEC=0 #optional
      - IMAGES=1 #optional
      - INFO=1 #optional
      - NETWORKS=1 #optional
      - NODES=0 #optional
      - PING=1 #optional
      - POST=0 #optional
      - PLUGINS=0 #optional
      - SECRETS=0 #optional
      - SERVICES=1 #optional
      - SESSION=0 #optional
      - SWARM=0 #optional
      - SYSTEM=0 #optional
      - TASKS=1 #optional
      - VERSION=1 #optional
      - VOLUMES=1 #optional
    networks:
      - internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    tmpfs:
      - /run
