---
name: gift-manager

networks:
  frontend:
    external: true

services:
  giftmanager:
    image: icbest/giftmanager:latest
    container_name: giftmanager
    security_opt:
      - no-new-privileges:true
    networks:
      - frontend
    restart: unless-stopped
    volumes:
      - ./data:/app/data/
    labels:
      traefik.enable: true
      traefik.external: true
      traefik.http.services.giftmanager-prod-1.loadBalancer.server.port: 5000
      traefik.http.routers.giftmanager-prod-1-http.entrypoints: web
      traefik.http.routers.giftmanager-prod-1-http.rule: Host(`secret-santa.jakerob.pro`)
      traefik.http.routers.giftmanager-prod-1-https.entrypoints: websecure
      traefik.http.routers.giftmanager-prod-1-https.rule: Host(`secret-santa.jakerob.pro`)
      traefik.http.routers.giftmanager-prod-1-https.tls: true
      traefik.http.routers.giftmanager-prod-1-https.tls.certresolver: production
