---
name: jellyfin

networks:
  frontend:
    external: true

volumes:
  cache:
    name: jellyfin_cache
  config:
    name: jellyfin_config
    driver: local
    driver_opts:
      type: nfs
      o: addr=lhr1-storage-1.jakerob.pro,nfsvers=4.1,soft,nolock,rw
      device: ":/mnt/default-pool/encrypted/container-volumes/jellyfin_config"

services:
  jellyfin:
    image: docker.io/jellyfin/jellyfin:10
    container_name: jellyfin
    hostname: jellyfin-lhr1
    user: "${DOCKER_USER_ID:-2003}:${DOCKER_GROUP_ID:-2003}"
    restart: unless-stopped
    environment:
      PUID: "${DOCKER_USER_ID:-2003}"
      PGID: "${DOCKER_GROUP_ID:-2003}"
      TZ: Europe/London
      JELLYFIN_PublishedServerUrl: https://jellyfin.lhr1.jakerob.pro
    networks:
      - frontend
    # devices:
    #   - /dev/dri:/dev/dri
    volumes:
      - config:/config
      - cache:/cache
      - /media/jellydata:/jellydata
    # group_add:
    #   - ${HARDWARE_VIDEO_GROUP_ID:-993} # get this from ls -g /dev/dri
    labels:
      traefik.enable: true
      traefik.http.services.jellyfin-prod-1.loadBalancer.server.port: 8096
      traefik.http.routers.jellyfin-prod-1-http.entrypoints: web
      traefik.http.routers.jellyfin-prod-1-http.rule: Host(`jellyfin.jakerob.pro`)
      traefik.http.routers.jellyfin-prod-1-http.middlewares: "websecure-redirect-permanent@file"
      traefik.http.routers.jellyfin-prod-1-https.entrypoints: websecure
      traefik.http.routers.jellyfin-prod-1-https.rule: Host(`jellyfin.jakerob.pro`)
      traefik.http.routers.jellyfin-prod-1-https.tls: true
      traefik.http.routers.jellyfin-prod-1-https.tls.certresolver: cloudflare
