$ANSIBLE_VAULT;1.1;AES256
63333464376338346538306365633532343138393861643464346438346438613232653931303665
3561333432363234323933326332336434656334393465350a303466653662383639643764643138
37653632373637386665373635666233633231366339316164616162346435623739393832366238
3139333661373361360a663765333530616561643838363966626332613437643232353931633233
38646339373761323230326437393437666565363761303032616261633761343031396234386630
37333637303330623337323463323263336462323061623062383236373761386638333531363430
35343032353138326334333766323336363862363362663832383030316466633932333834626138
38316238323961356233666664616133313263303364383362613861303139643839313433363539
36373035623461393964663466393662396262383137373439336330326635643838343632386435
66303936623431616666653531646439373232316162343433613461353066393134373165323136
66346162313161666165306436643264336339336165316631353562656366626464646337663662
37396132613563303433316235646365616161666137356364356462376238643935353163393231
63643339643163623436653962366234623138333035333061383539646633333231316266333434
38316437643161616263373631393764646163343366643538663231356466623861386139303635
36373562616365303563346634396364393263356461616235616662353933653663643932646365
33346134326235656334623238356637356539396139343666666162636566366162636266623038
35623362336337373761666366356233656236653433323234313136343433656636616564633964
3162396666623931333937323833333132386139393835393331
