---
name: myspeed

networks:
  frontend:
    external: true

services:
  myspeed:
    image: docker.io/germannewsmaker/myspeed:1.0.9
    container_name: myspeed
    security_opt:
      - no-new-privileges:true
    user: "${DOCKER_USER_ID:-2017}:${DOCKER_GROUP_ID:-2017}"
    restart: unless-stopped
    networks:
      - frontend
    volumes:
      - ./data:/myspeed/data
    environment:
      PUID: "${DOCKER_USER_ID:-2017}"
      PGID: "${DOCKER_GROUP_ID:-2017}"
    labels:
      traefik.enable: true
      traefik.http.services.myspeed-prod-1.loadBalancer.server.port: 5216
      traefik.http.routers.myspeed-prod-1-http.entrypoints: web
      traefik.http.routers.myspeed-prod-1-http.rule: Host(`myspeed.lhr1.jakerob.pro`)
      traefik.http.routers.myspeed-prod-1-http.middlewares: "websecure-redirect-permanent@file"
      traefik.http.routers.myspeed-prod-1-https.entrypoints: websecure
      traefik.http.routers.myspeed-prod-1-https.rule: Host(`myspeed.lhr1.jakerob.pro`)
      traefik.http.routers.myspeed-prod-1-https.tls: true
      traefik.http.routers.myspeed-prod-1-https.tls.certresolver: cloudflare
