---
name: portainer

networks:
  frontend:
    external: true

services:
  portainer:
    image: docker.io/portainer/portainer-ce:2.26.1-alpine
    container_name: portainer
    command: "-H unix:///var/run/docker.sock"
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - frontend
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      traefik.enable: true
      traefik.docker.network: frontend
      traefik.http.services.portainer-prod-1.loadbalancer.server.port: '9000'
      traefik.http.services.portainer-prod-1.loadbalancer.server.scheme: http
      traefik.http.routers.portainer-prod-1-http.entrypoints: web
      traefik.http.routers.portainer-prod-1-http.rule: Host(`portainer.iad1vpn.jakerob.pro`)
      traefik.http.routers.portainer-prod-1-https.entrypoints: websecure
      traefik.http.routers.portainer-prod-1-https.rule: Host(`portainer.iad1vpn.jakerob.pro`)
      traefik.http.routers.portainer-prod-1-https.tls: true
      traefik.http.routers.portainer-prod-1-https.tls.certresolver: cloudflare
