---
name: dns

networks:
  frontend:
    external: true

volumes:
  pihole_data:

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/

services:
  pihole:
    image: docker.io/pihole/pihole:latest
    container_name: pihole
    hostname: pihole-lhr1-pi-1
    cap_add:
      # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      # Required if you are using Pi-hole as your DHCP server, else not needed
      # - NET_ADMIN
      # Required if you are using Pi-hole as your NTP client to be able to set the host's system time
      # - SYS_TIME
      # Optional, if Pi-hole should get some more processing time
      - SYS_NICE
    restart: unless-stopped

    ports:
      # DNS Ports
      - "${IP:-192.168.42.2}:53:53/tcp"
      - "${IP:-192.168.42.2}:53:53/udp"
      # Uncomment the line below if you are using Pi-hole as your DHCP server
      #- "67:67/udp"
      # Uncomment the line below if you are using Pi-hole as your NTP server
      #- "123:123/udp"
    networks:
      - frontend
    environment:
      # Set the appropriate timezone for your location (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones), e.g:
      TZ: Europe/London
      # Set a password to access the web interface. Not setting one will result in a random password being assigned
      FTLCONF_webserver_api_password: "${PIHOLE_PASSWORD}"
      FTLCONF_dns_upstreams: 1.1.1.1;1.0.0.1
      # If using Docker's default `bridge` network setting the dns listening mode should be set to 'ALL'
      FTLCONF_dns_listeningMode: ALL
    # Volumes store your data between container upgrades
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - pihole_data:/etc/pihole
      # Uncomment the below if you have custom dnsmasq config files that you want to persist. Not needed for most starting fresh with Pi-hole v6. If you're upgrading from v5 you and have used this directory before, you should keep it enabled for the first v6 container start to allow for a complete migration. It can be removed afterwards. Needs environment variable FTLCONF_misc_etc_dnsmasq_d: 'true'
      #- './etc-dnsmasq.d:/etc/dnsmasq.d'
    labels:
      traefik.enable: true
      traefik.http.services.pihole-prod-1.loadbalancer.server.port: "80"
      traefik.http.routers.pihole-prod-1-http.entrypoints: web
      traefik.http.routers.pihole-prod-1-http.rule: Host(`pihole.lhr1.jakerob.pro`)
      traefik.http.routers.pihole-prod-1-http.middlewares: "websecure-redirect-permanent@file"
      traefik.http.routers.pihole-prod-1-https.entrypoints: websecure
      traefik.http.routers.pihole-prod-1-https.rule: Host(`pihole.lhr1.jakerob.pro`)
      traefik.http.routers.pihole-prod-1-https.tls: true
      traefik.http.routers.pihole-prod-1-https.tls.certresolver: cloudflare
  nebula-sync:
    image: ghcr.io/lovelaze/nebula-sync:latest
    container_name: nebula-sync
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    environment:
      TZ: Europe/London
      CLIENT_SKIP_TLS_VERIFICATION: "true"
      PRIMARY: "https://pihole.lhr1.jakerob.pro|${PIHOLE_PASSWORD}"
      REPLICAS: "https://pihole2.lhr1.jakerob.pro|${PIHOLE2_PASSWORD}"
      FULL_SYNC: "false"
      SYNC_CONFIG_DNS: "true"
      SYNC_CONFIG_DNS_EXCLUDE: listeningMode
      CRON: "0 * * * *"
