---
name: prometheus

networks:
  frontend:
    external: true

volumes:
  prometheus-data:
    driver: local

services:
  prometheus:
    image: docker.io/prom/prometheus:v2.37.9
    container_name: prometheus
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    restart: unless-stopped
    networks:
      - frontend
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - prometheus-data:/prometheus
    labels:
      traefik.enable: true
      traefik.http.routers.prometheus-prod-1-http.entrypoints: web
      traefik.http.routers.prometheus-prod-1-http.rule: Host(`prometheus.slc1.jakerob.pro`)
      traefik.http.routers.prometheus-prod-1-https.entrypoints: websecure
      traefik.http.routers.prometheus-prod-1-https.rule: Host(`prometheus.slc1.jakerob.pro`)
      traefik.http.routers.prometheus-prod-1-https.tls: true
      traefik.http.routers.prometheus-prod-1-https.tls.certresolver: cloudflare
