---
name: uptimekuma

networks:
  frontend:
    external: true

services:
  uptimekuma:
    image: docker.io/louislam/uptime-kuma:2-rootless
    container_name: uptimekuma
    user: "${DOCKER_USER_ID:-2018}:${DOCKER_GROUP_ID:-2018}"
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - frontend
    volumes:
      - ./data:/app/data
    labels:
      traefik.enable: true
      traefik.http.routers.uptimekuma-prod-1-http.entrypoints: web
      traefik.http.routers.uptimekuma-prod-1-http.rule: Host(`uptime.lhr1.jakerob.pro`)
      traefik.http.routers.uptimekuma-prod-1-http.middlewares: "websecure-redirect-permanent@file"
      traefik.http.routers.uptimekuma-prod-1-https.entrypoints: websecure
      traefik.http.routers.uptimekuma-prod-1-https.rule: Host(`uptime.lhr1.jakerob.pro`)
      traefik.http.routers.uptimekuma-prod-1-https.tls: true
      traefik.http.routers.uptimekuma-prod-1-https.tls.certresolver: cloudflare
