---
name: omada-controller

networks:
  frontend:
    external: true

volumes:
  omada-data:
  omada-logs:

services:
  omada-controller:
    image: docker.io/mbentley/omada-controller:5.15
    container_name: omada-controller
    restart: unless-stopped
    ports:
      - 27001:27001/udp
      - 29810:29810/udp
      - 29811-29816:29811-29816
    environment:
      PUID: '1000'
      PGID: '1000'
      MANAGE_HTTP_PORT: '8088'
      MANAGE_HTTPS_PORT: '8043'
      PORTAL_HTTP_PORT: '8088'
      PORTAL_HTTPS_PORT: '8843'
      PORT_APP_DISCOVERY: '27001'
      PORT_ADOPT_V1: '29812'
      PORT_UPGRADE_V1: '29813'
      PORT_MANAGER_V1: '29811'
      PORT_MANAGER_V2: '29814'
      PORT_DISCOVERY: '29810'
      PORT_TRANSFER_V2: '29815'
      PORT_RTTY: '29816'
      SHOW_SERVER_LOGS: "true"
      SHOW_MONGODB_LOGS: "false"
      SSL_CERT_NAME: tls.crt
      SSL_KEY_NAME: tls.key
      TZ: Etc/UTC
    networks:
      - frontend
    volumes:
      - omada-data:/opt/tplink/EAPController/data
      - omada-logs:/opt/tplink/EAPController/logs
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    stop_grace_period: 60s
    labels:
      traefik.enable: true
      traefik.http.services.omada-prod-1.loadBalancer.server.port: 8088
      traefik.http.routers.omada-prod-1-http.entrypoints: web
      traefik.http.routers.omada-prod-1-http.rule: Host(`omada.lhr1.jakerob.pro`)
      traefik.http.routers.omada-prod-1-http.middlewares: "websecure-redirect-permanent@file"
      traefik.http.routers.omada-prod-1-https.entrypoints: websecure
      traefik.http.routers.omada-prod-1-https.rule: Host(`omada.lhr1.jakerob.pro`)
      traefik.http.routers.omada-prod-1-https.tls: true
      traefik.http.routers.omada-prod-1-https.tls.certresolver: cloudflare


